Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2010"
  config.vm.provider "hyperv" do |h|
    h.vmname = "photon.ai"
    h.cpus = 4
    h.maxmemory = 9216
    h.linked_clone = true
    h.enable_virtualization_extensions = true
    # h.vm_integration_services = {
    #   guest_service_interface: true,
    #   CustomVMSRV: true
    # }
  end

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provision "shell", inline: <<-SHELL
    echo 'vagrant:admin' | chpasswd
  SHELL
end
